name: Ansible CI/CD demo video pipeline

on:
  push:
    paths:
      - 'WEEK5/Playbook/**'
  workflow_dispatch:

jobs:
  ansible:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: ansible-playbook -i WEEK5/Playbook/inventory.ini WEEK5/Playbook/apache-ci.yaml
