name: Ansible CI/CD

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint + Dry Run
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible & ansible-lint
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint WEEK5/Playbook/apache-run.yaml

      - name: Dry-run playbook
        run: ansible-playbook WEEK5/Playbook/apache-run.yaml --check

  deploy:
    name: Deploy Apache
    runs-on: self-hosted
    needs: lint-and-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible

      - name: Run playbook
        run: ansible-playbook WEEK5/Playbook/apache-run.yaml
