name: Terraform CI/CD

on:
  push:
    paths:
      - 'WEEK5/Terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3

      - name: Terraform Format Check
        run: terraform -chdir=./WEEK5/Terraform fmt -check

      - name: Terraform Init
        run: terraform -chdir=./WEEK5/Terraform init

      - name: Terraform Validate
        run: terraform -chdir=./WEEK5/Terraform validate

      - name: Terraform Plan
        run: terraform -chdir=./WEEK5/Terraform plan

        
      - name: Terraform Apply
        run: terraform -chdir=./WEEK5/Terraform apply -auto-approve
